jwt:
    expiry:
        time:
            InHours: 10
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bookmyshow?useSSL=false
        username: root
        password: root
        #comment the above three properties and uncomment the below ones when deploying to K8s
        #url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
        #username: ${DB_USERNAME}
        #password: ${DB_PASSWORD}
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
